Import module:

In [2]:
import numpy as np

# Array with intiger values:

In [3]:
array_int = np.array([[1,2],[2,8]])

Methods to show array:

In [ ]:
array_int

array([1, 2, 3])

In [4]:
print(array_int)

[[1 2]
 [2 8]]


Type of values in array:

In [7]:
array_int.dtype

dtype('int64')

#Array with float values:

In [8]:
array_float = np.array([[1.3,2.5],[2.2,8.8]])

Methods to show array:

In [9]:
array_float

array([[1.3, 2.5],
       [2.2, 8.8]])

In [10]:
print(array_float)

[[1.3 2.5]
 [2.2 8.8]]


Type of values in array:

In [11]:
array_float.dtype

dtype('float64')

#Array with int values converted to float:

In [12]:
array_float_conv = np.array([[1,3,2,5],[2,2,8,8]],dtype='float')

Methods to show array:

In [14]:
array_float_conv

array([[1., 3., 2., 5.],
       [2., 2., 8., 8.]])

In [15]:
print(array_float_conv)

[[1. 3. 2. 5.]
 [2. 2. 8. 8.]]


Type of values in array:

In [16]:
array_float_conv.dtype

dtype('float64')

#Array with boolean values:

In [21]:
array_bool = np.array([[True,False,False],[True,True,False]])

Methods to show array:

In [22]:
array_bool

array([[ True, False, False],
       [ True,  True, False]])

In [23]:
print(array_bool)

[[ True False False]
 [ True  True False]]


Type of values in array:

In [24]:
array_bool.dtype

dtype('bool')