Import module:

In [1]:
import numpy as np

Set always the same random values:

In [4]:
np.random.seed(0)

Array with normal distributed 10 elements:

In [5]:
np.random.randn(10)

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

Array with normal distributed values of shape 2 rows and 5 columns:

In [9]:
np.random.randn(2,5)

array([[-0.67246045, -0.35955316, -0.81314628, -1.7262826 ,  0.17742614],
       [-0.40178094, -1.63019835,  0.46278226, -0.90729836,  0.0519454 ]])

Array with values between 0 - 1 of shape 2 array 2 rows and 5 columns:

In [11]:
np.random.rand(2,2,5)

array([[[0.5759465 , 0.9292962 , 0.31856895, 0.66741038, 0.13179786],
        [0.7163272 , 0.28940609, 0.18319136, 0.58651293, 0.02010755]],

       [[0.82894003, 0.00469548, 0.67781654, 0.27000797, 0.73519402],
        [0.96218855, 0.24875314, 0.57615733, 0.59204193, 0.57225191]]])

Array with  intiger values between 11 - 22 of shape 2 rows and 5 columns:

In [12]:
np.random.randint(
    low =11,
    high = 23,
    size = (2,2,5)
)

array([[[15, 14, 11, 15, 14],
        [22, 17, 20, 22, 19]],

       [[11, 19, 16, 20, 11],
        [20, 17, 16, 14, 12]]])

Array with text values choosed randomly from list to create array shape of (2,3,4):

In [14]:
np.random.choice(['sql','excel','pandas'],size = (2,3,4))

array([[['sql', 'sql', 'sql', 'excel'],
        ['pandas', 'excel', 'excel', 'sql'],
        ['sql', 'excel', 'pandas', 'sql']],

       [['pandas', 'pandas', 'excel', 'excel'],
        ['excel', 'pandas', 'sql', 'sql'],
        ['excel', 'sql', 'pandas', 'pandas']]], dtype='<U6')