## Import modules:

In [8]:
import numpy as np

# Various method of create array:

# **Array filled by 0:**

In [14]:
zero_array = np.zeros(shape= (2,3,4),dtype = 'int8')

In [15]:
zero_array

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int8)

# Array filled by 1:

In [19]:
ones_array = np.ones(shape = (2,3,4),dtype = 'uint8')

In [20]:
ones_array

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=uint8)

# Array filed by 5:

In [24]:
fives_array = np.full(shape = (2,3,4), fill_value=5,dtype='float')

In [25]:
fives_array

array([[[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]],

       [[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]]])

In [26]:
np.linspace(0,4,5)

array([0., 1., 2., 3., 4.])

# Array with values from 0 to 8:

Using arrange:

In [28]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
np.arange(
    start = 0,
    stop = 9,
    step = 1,
    dtype = 'int'
)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

Using linspace:

In [35]:
np.linspace(start = 0,
            stop = 8,
            num = 9,
            dtype = 'int')

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

# Array reshape function:

Create array:

In [36]:
array = np.arange(20)

In [37]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Reshaped array into 3D:

In [38]:
array.reshape(2,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])