Importing module:

In [1]:
import numpy as np

Create random array:

In [7]:
A = np.random.randn(2,3,5)*10
A

array([[[ -2.53649574,  -1.30472207,  -2.86646859,  -6.20337343,
          14.58024803],
        [ 11.97057962, -11.52084724,  -8.82077775,   2.62815668,
          -1.05685565],
        [ 21.6142583 , -17.01802523,  -0.99707347,  -1.13903019,
           4.07363221]],

       [[  3.48578805,   8.96934399,  12.73415048,  23.7974183 ,
          -2.65527415],
        [  4.26207328,   0.0256276 ,  -6.12306545,  -7.45594606,
          -1.29221987],
        [  3.07844116,   0.29804879,   4.54582385,  -1.92554129,
           3.62264059]]])

# Mathematic functions:

Expotencial of array:

In [8]:
np.exp(A)

array([[[7.91432528e-02, 2.71247912e-01, 5.68995075e-02, 2.02259602e-03,
         2.14843028e+06],
        [1.58036235e+05, 9.92109518e-06, 1.47633494e-04, 1.38482197e+01,
         3.47546904e-01],
        [2.43754764e+09, 4.06598292e-08, 3.68957628e-01, 3.20129337e-01,
         5.87700403e+01]],

       [[3.26481454e+01, 7.85844468e+03, 3.39133964e+05, 2.16315407e+10,
         7.02795687e-02],
        [7.09569444e+01, 1.02595881e+00, 2.19172703e-03, 5.77994586e-04,
         2.74660396e-01],
        [2.17245110e+01, 1.34722751e+00, 9.42380334e+01, 1.45796817e-01,
         3.74362913e+01]]])

Square root of array:

In [10]:
np.sqrt(abs(A))

array([[[1.59263798, 1.14224431, 1.69306485, 2.49065723, 3.8184091 ],
        [3.45985254, 3.39423736, 2.96997942, 1.62115906, 1.02803485],
        [4.64911371, 4.12529093, 0.99853566, 1.06725357, 2.01832411]],

       [[1.86702653, 2.99488631, 3.56849415, 4.87825976, 1.6295012 ],
        [2.06447894, 0.16008621, 2.47448286, 2.73055783, 1.13675849],
        [1.75454871, 0.54593845, 2.13209377, 1.38763875, 1.90332356]]])

Maximal value in array:

In [40]:
np.max(A)

23.79741830221159

Minimal value in array:

In [41]:
np.min(A)

-17.01802522827184

Mean of array:

In [42]:
np.mean(A)

1.5590171583812775

Median of array:

In [43]:
np.median(A)

-0.48572293812558165

Standard deviation of array:

In [44]:
np.std(A)

8.794200302888985

# Logical functions:

Check if is all values are diffrent then 0:

In [23]:
np.all(A)

True

In [25]:
np.all([1,2,0,3])

False

Check if all values are not 0:

In [26]:
np.any(A)

True

In [27]:
np.any([0,0])

False

# Index functions:

Examped array:

In [38]:
np.arange(5)

array([0, 1, 2, 3, 4])

Index number of lowest value in array:

In [34]:
np.argmin(np.arange(5))

0

The lowest value:

In [35]:
np.arange(5)[np.argmin(np.arange(5))]

0

Index number of highest value in array:

In [33]:
np.argmax(np.arange(5))

4

The highest value:

In [37]:
np.arange(5)[np.argmax(np.arange(5))]

4

Array with sorted index number from lowest to highest value:


In [39]:
np.argsort(np.arange(5))

array([0, 1, 2, 3, 4])

Array with sorted index number from highest to lowest value:


In [54]:
np.argsort(np.arange(5))[::-1]

array([4, 3, 2, 1, 0])