Import numpy module:

In [3]:
import numpy as np

Sample array:

In [5]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# Indexing array:

Value of index number 5:

In [7]:
A[5]

5

Values of index number from 3 to 9:

In [8]:
A[3:9]

array([3, 4, 5, 6, 7, 8])

First 10 values from array:

In [9]:
A[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Last 3 values from array:

In [11]:
A[-3:]

array([17, 18, 19])

Ever third values from array starting from index number 2 and finish on index number 15:

In [21]:
A[2:15:3]

array([[10, 11, 12, 13, 14]])

Array reshape to 4 rows and 5 columns:

In [17]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Cutting values from 6 to 8 and 11 to 13:

In [23]:
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

Replace value 7 with -5:

In [25]:
A[1,2] = -5

Array after replace:

In [27]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, -5,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Reshape array to have 2 tables with 5 rows and 2 columns:

In [29]:
A = A.reshape(2,5,2)
A

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6, -5],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

The second table from array:

In [30]:
A[1]

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

Create more complicated array:

In [32]:
B = np.random.randint(low = -10, high = 10, size = (3,5,5))
B

array([[[  2,   8,  -6,  -3, -10],
        [ -7,   6,   3,   5,  -6],
        [  1,  -2,   4,   6,   5],
        [ -8,  -1,  -4,  -5,  -5],
        [ -7,   5,  -2,  -8,   0]],

       [[ -8,  -4,  -6,   7,   2],
        [  8,  -6,  -9,  -4,  -8],
        [ -8,   7,  -7,  -2,   6],
        [  5,  -9,   1,  -3,   8],
        [  2,   7,  -4,   1,   5]],

       [[ -5,  -7,  -1,   0,   9],
        [-10,  -1,   2,   2,   4],
        [ -3,   7,   2,   4,  -9],
        [ -7, -10,   5,  -2,  -2],
        [ -1,  -7,   9,   4, -10]]])

Show the value from middle of second table:

In [33]:
B[1,2,2]

-7

Show every second value in array:

In [34]:
B[::2,::2,::2]

array([[[  2,  -6, -10],
        [  1,   4,   5],
        [ -7,  -2,   0]],

       [[ -5,  -1,   9],
        [ -3,   2,  -9],
        [ -1,   9, -10]]])