Import NumPy module:

In [56]:
import numpy as np
np.set_printoptions(precision= 4, suppress= True)

# 2-D Vector

Create vector:

In [4]:
v = np.array([0,4])
v

array([0, 4])

Norm of vector (long of vector):

In [5]:
np.linalg.norm(v)

4.0

# Operations on points:

Create two points in 2D space:


In [9]:
p1 = np.array([3,-5])
p1

array([ 3, -5])

In [10]:
p2 = np.array([-4,2])
p2

array([-4,  2])

Distance between two points:

In [11]:
np.linalg.norm(p1-p2)

9.899494936611665

Create two points in 3D space:

In [12]:
p1 = np.array([3,-5,0])
p1

array([ 3, -5,  0])

In [13]:
p2 = np.array([-4,0,2])
p2

array([-4,  0,  2])

Distance between two points:

In [15]:
np.linalg.norm(p1-p2)

8.831760866327848

# Dot products of two matrix:

Two random arrays:

In [17]:
a1 = np.random.randint(-10,10,(3,4))
a1

array([[ -7,   2,   0,  -3],
       [ -7,   1,  -9,  -1],
       [-10,  -4,  -6,  -6]])

In [19]:
a2 = np.random.randint(-10,10,(4,5))
a2

array([[ -9,   2,  -5, -10,  -1],
       [ -2,   1,  -2, -10,  -7],
       [ -4,   0,   5,  -6,   0],
       [ -7,   0,  -9,   0,   4]])

Methods of calcuate the dot product:

In [22]:
a1 @ a2

array([[ 80, -12,  58,  50, -19],
       [104, -13,  -3, 114,  -4],
       [164, -24,  82, 176,  14]])

In [23]:
np.dot(a1,a2)

array([[ 80, -12,  58,  50, -19],
       [104, -13,  -3, 114,  -4],
       [164, -24,  82, 176,  14]])

In [24]:
a1.dot(a2)

array([[ 80, -12,  58,  50, -19],
       [104, -13,  -3, 114,  -4],
       [164, -24,  82, 176,  14]])

Determinant of an array:

In [29]:
np.random.rand(4,4)

array([[0.40101443, 0.43622507, 0.29792698, 0.88894798],
       [0.42804682, 0.40018364, 0.16372467, 0.89749788],
       [0.11820884, 0.85351512, 0.42573997, 0.36656093],
       [0.14538092, 0.44793271, 0.59856211, 0.28463742]])

In [27]:
np.linalg.det(np.random.rand(4,4))

-0.03746176466674798

Trace of array:

In [31]:
np.trace(np.random.rand(4,4))

1.0238063057998268

Create 2-D array with ones on the diagonal and zeros elsewhere (shape 3x3 rows x columns):

In [33]:
np.eye(3,3,dtype='int8')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

Create 2-D array with ones on the diagonal and zeros elsewhere (shape 3x4 rows x columns):

In [34]:
np.eye(3,4,dtype='bool')

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

Calulate the inverse of a matrix:

In [38]:
A = np.random.randint(-10,10,(4,4))
A

array([[-10,  -1,  -7,   7],
       [ -1,   0,  -3,  -6],
       [  5,   1,   7,  -7],
       [ -7,   0,  -5,  -6]])

In [54]:
B = np.linalg.inv(A)
B

array([[-2.00000000e-01, -8.88178420e-17, -2.00000000e-01,
        -0.00000000e+00],
       [-5.06666667e+00, -6.41666667e+00, -4.06666667e+00,
         5.25000000e+00],
       [ 6.00000000e-01,  5.00000000e-01,  6.00000000e-01,
        -5.00000000e-01],
       [-2.66666667e-01, -4.16666667e-01, -2.66666667e-01,
         2.50000000e-01]])

Check if AxB = BxA

In [60]:
A @ B

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [-0., -0.,  1., -0.],
       [ 0.,  0.,  0.,  1.]])

In [61]:
B @ A

array([[ 1., -0., -0.,  0.],
       [ 0.,  1.,  0., -0.],
       [-0.,  0.,  1., -0.],
       [ 0.,  0.,  0.,  1.]])

Methods of transpose array:

In [63]:
A

array([[-10,  -1,  -7,   7],
       [ -1,   0,  -3,  -6],
       [  5,   1,   7,  -7],
       [ -7,   0,  -5,  -6]])

In [62]:
A.T

array([[-10,  -1,   5,  -7],
       [ -1,   0,   1,   0],
       [ -7,  -3,   7,  -5],
       [  7,  -6,  -7,  -6]])

In [64]:
np.transpose(A)

array([[-10,  -1,   5,  -7],
       [ -1,   0,   1,   0],
       [ -7,  -3,   7,  -5],
       [  7,  -6,  -7,  -6]])

# System of equations:

Example of equations:

2x	+	y	−	2z	=	3

x	−	y	−	z	=	0

x	+	y	+	3z	=	12

Create array of shells:

In [75]:
A = np.array([[2,1,-2],
              [1,-1,-1],
              [1,1,3]])
A

array([[ 2,  1, -2],
       [ 1, -1, -1],
       [ 1,  1,  3]])

Check if numbers of column and rows is the same:

In [80]:
print('Yes') if A.shape[0] ==A.shape[1] else print("No")

Yes


Row and column names are the same so we can calculate the inverse of a matrix A:

In [81]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.1667,  0.4167,  0.25  ],
       [ 0.3333, -0.6667, -0.    ],
       [-0.1667,  0.0833,  0.25  ]])

Create array of results:

In [85]:
B = np.array([[3],[0],[12]])
B

array([[ 3],
       [ 0],
       [12]])

Compute the solution of equations:

In [86]:
A_inv @ B

array([[3.5],
       [1. ],
       [2.5]])

Solution:

In [91]:
letter = ['x','y','z']
for idx, val in enumerate(A_inv @ B):
    print(f'{letter[idx]} is equal: {val}')

x is equal: [3.5]
y is equal: [1.]
z is equal: [2.5]
