Import modules:

In [6]:
import pandas as pd
import pandas_datareader as pdr
import numpy as np

# Get data:

Import Amazon stock data: 

In [10]:
df = pdr.DataReader(name='AMZN', data_source='yahoo')
df

High          Low  ...   Volume    Adj Close
Date                                  ...                      
2015-11-06   662.260010   652.000000  ...  4092200   659.369995
2015-11-09   661.960022   647.849976  ...  4048800   655.489990
2015-11-10   660.000000   647.260010  ...  3489500   659.679993
2015-11-11   675.960022   663.250000  ...  5387300   673.250000
2015-11-12   675.640015   664.219971  ...  4284700   665.599976
...                 ...          ...  ...      ...          ...
2020-10-28  3264.020020  3162.469971  ...  5588300  3162.780029
2020-10-29  3257.250000  3164.000000  ...  6596500  3211.010010
2020-10-30  3167.000000  3019.000000  ...  8386400  3036.149902
2020-11-02  3079.709961  2950.120117  ...  7257400  3004.479980
2020-11-03  3074.899902  2980.979980  ...  4874400  3048.409912

[1257 rows x 6 columns]

Remove last column:

In [12]:
df = df.iloc[:,:-1] 
df

High          Low         Open        Close   Volume
Date                                                                   
2015-11-06   662.260010   652.000000   655.000000   659.369995  4092200
2015-11-09   661.960022   647.849976   658.650024   655.489990  4048800
2015-11-10   660.000000   647.260010   651.010010   659.679993  3489500
2015-11-11   675.960022   663.250000   663.250000   673.250000  5387300
2015-11-12   675.640015   664.219971   673.000000   665.599976  4284700
...                 ...          ...          ...          ...      ...
2020-10-28  3264.020020  3162.469971  3249.300049  3162.780029  5588300
2020-10-29  3257.250000  3164.000000  3201.270020  3211.010010  6596500
2020-10-30  3167.000000  3019.000000  3157.750000  3036.149902  8386400
2020-11-02  3079.709961  2950.120117  3061.739990  3004.479980  7257400
2020-11-03  3074.899902  2980.979980  3018.530029  3048.409912  4874400

[1257 rows x 5 columns]

Take only last 10 rows:

In [13]:
df = df.iloc[-10:,:] 
df

High          Low         Open        Close   Volume
Date                                                                   
2020-10-21  3233.879883  3160.000000  3212.500000  3184.939941  4592700
2020-10-22  3198.750000  3121.939941  3189.870117  3176.399902  4212000
2020-10-23  3205.330078  3140.000000  3191.000000  3204.399902  3466700
2020-10-26  3282.979980  3153.300049  3198.739990  3207.040039  5901200
2020-10-27  3291.659912  3211.300049  3224.939941  3286.330078  4291000
2020-10-28  3264.020020  3162.469971  3249.300049  3162.780029  5588300
2020-10-29  3257.250000  3164.000000  3201.270020  3211.010010  6596500
2020-10-30  3167.000000  3019.000000  3157.750000  3036.149902  8386400
2020-11-02  3079.709961  2950.120117  3061.739990  3004.479980  7257400
2020-11-03  3074.899902  2980.979980  3018.530029  3048.409912  4874400

Create array with df values:

In [16]:
A = df.to_numpy()
A

array([[3.23387988e+03, 3.16000000e+03, 3.21250000e+03, 3.18493994e+03,
        4.59270000e+06],
       [3.19875000e+03, 3.12193994e+03, 3.18987012e+03, 3.17639990e+03,
        4.21200000e+06],
       [3.20533008e+03, 3.14000000e+03, 3.19100000e+03, 3.20439990e+03,
        3.46670000e+06],
       [3.28297998e+03, 3.15330005e+03, 3.19873999e+03, 3.20704004e+03,
        5.90120000e+06],
       [3.29165991e+03, 3.21130005e+03, 3.22493994e+03, 3.28633008e+03,
        4.29100000e+06],
       [3.26402002e+03, 3.16246997e+03, 3.24930005e+03, 3.16278003e+03,
        5.58830000e+06],
       [3.25725000e+03, 3.16400000e+03, 3.20127002e+03, 3.21101001e+03,
        6.59650000e+06],
       [3.16700000e+03, 3.01900000e+03, 3.15775000e+03, 3.03614990e+03,
        8.38640000e+06],
       [3.07970996e+03, 2.95012012e+03, 3.06173999e+03, 3.00447998e+03,
        7.25740000e+06],
       [3.07489990e+03, 2.98097998e+03, 3.01853003e+03, 3.04840991e+03,
        4.87440000e+06]])

## Statistics_functions

Sum of volume:

In [19]:
A[:,-1].sum()

55166600.0

Calulate sum of each column:

In [20]:
A.sum(axis = 0)

array([3.20554797e+04, 3.10631101e+04, 3.17056401e+04, 3.15219397e+04,
       5.51666000e+07])

Calulate sum of each row:

In [21]:
A.sum(axis = 1)

array([4605491.31982422, 4224686.95996094, 3479440.72998047,
       5914042.06005859, 4304014.22998047, 5601138.57006836,
       6609333.5300293 , 8398779.89990234, 7269496.05004883,
       4886522.81982422])

Print minimum and maximum value for each column:

In [31]:
for num in range(0,A.shape[1]):
    print(f'For column number: {num}, Max value is: {A[:,num].max()}\
    , Min value is: {A[:,num].min()}')

For column number: 0, Max value is: 3291.659912109375    , Min value is: 3074.89990234375
For column number: 1, Max value is: 3211.300048828125    , Min value is: 2950.1201171875
For column number: 2, Max value is: 3249.300048828125    , Min value is: 3018.530029296875
For column number: 3, Max value is: 3286.330078125    , Min value is: 3004.47998046875
For column number: 4, Max value is: 8386400.0    , Min value is: 3466700.0


Compute mean, median, std and var for each column:

In [36]:
for num in range(0,A.shape[1]):
    print('For column: ' + str(num))
    print(f'Mean: {np.mean(A,axis = 0)[num]}, Median: {np.median(A,0)[num]} '\
          + f'Std: {np.std(A,0)[num]}, Var: {np.var(A,0)[num]}', end = '\n\n')

For column: 0
Mean: 3205.5479736328125, Median: 3219.60498046875 Std: 73.98789668347025, Var: 5474.208855643868

For column: 1
Mean: 3106.3110107421876, Median: 3146.6500244140625 Std: 84.6763899195108, Var: 7170.09100980103

For column: 2
Mean: 3170.564013671875, Median: 3194.8699951171875 Std: 69.68718013243544, Var: 4856.303074810506

For column: 3
Mean: 3152.1939697265625, Median: 3180.669921875 Std: 86.6097235702893, Var: 7501.244216921926

For column: 4
Mean: 5516660.0, Median: 5231350.0 Std: 1457997.1633717262, Var: 2125755728400.0

