Import module:

In [4]:
import numpy as np

# One-dimensional array:

Create a one-dimensional array:

In [25]:
one_dim = np.array([1,2])

Methods to show array:

In [7]:
one_dim

array([1, 2, 3])

In [8]:
print(one_dim)

[1 2 3]


Type of one-dimensional array:

In [9]:
type(one_dim)

numpy.ndarray

Numbers of row in array:

In [11]:
one_dim.ndim

1

Numbers of element in array:

In [22]:
one_dim.size

2

Dimension of array:

In [23]:
one_dim.shape

(2,)

Data type in array:

In [27]:
one_dim.dtype

dtype('int64')

# Two-dimensional array:

Create a two-dimensional array:

In [30]:
two_dimens = np.array([[-5.9,-11.8,-15.2],[12.6,24.6,31.5]])

Methods to show created array:

In [31]:
two_dimens

array([[ -5.9, -11.8, -15.2],
       [ 12.6,  24.6,  31.5]])

In [32]:
print(two_dimens)

[[ -5.9 -11.8 -15.2]
 [ 12.6  24.6  31.5]]


Type of two-dimensional array:

In [33]:
type(two_dimens)

numpy.ndarray

Numbers of row in array:

In [34]:
two_dimens.ndim

2

Numbers of element in array:

In [35]:
two_dimens.size

6

Dimension of array:

In [36]:
two_dimens.shape

(2, 3)

Data type in array:

In [37]:
two_dimens.dtype

dtype('float64')

# Three-dimensional array:

Create a three-dimensional array:

In [59]:
three_dimens = np.array([
                         [[-1.9,-1.8],[-5.9,-15.2]],
                         [[-1.9,-1.8],[-5.9,-15.2]]
                         ])

Methods to show created array:

In [60]:
three_dimens

array([[[ -1.9,  -1.8],
        [ -5.9, -15.2]],

       [[ -1.9,  -1.8],
        [ -5.9, -15.2]]])

In [61]:
print(three_dimens)

[[[ -1.9  -1.8]
  [ -5.9 -15.2]]

 [[ -1.9  -1.8]
  [ -5.9 -15.2]]]


Type of three-dimensional array:

In [62]:
type(three_dimens)

numpy.ndarray

Numbers of row in array:

In [63]:
three_dimens.ndim

3

Numbers of element in array:

In [64]:
three_dimens.size

8

Dimension of array:

In [65]:
three_dimens.shape

(2, 2, 2)

Data type in array:

In [66]:
three_dimens.dtype

dtype('float64')