Importing module:

In [1]:
import numpy as np

## Operation on the same size array:

Create arrays:

In [3]:
A = np.array([2,5,-2,3])
B = np.array([3,-7,-2,0])

Addition:

In [4]:
A+B

array([ 5, -2, -4,  3])

In [11]:
np.add(A,B)

array([ 5, -2, -4,  3])

Subtraction:

In [5]:
A-B

array([-1, 12,  0,  3])

In [13]:
np.subtract(A,B)

array([-1, 12,  0,  3])

Multiplication:

In [6]:
A*B

array([  6, -35,   4,   0])

In [14]:
np.multiply(A,B)

array([  6, -35,   4,   0])

Division(Cause error because one value in zero):

In [8]:
A/B

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ 0.66666667, -0.71428571,  1.        ,         inf])

In [15]:
np.divide(A,B)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ 0.66666667, -0.71428571,  1.        ,         inf])

# Advanced operations:

Arrays assigment:

In [23]:
A = np.array([[2,5],[10,8]])
B = np.array([[3,-7,],[0,4]])

Complex equation:

In [24]:
(np.abs(A) * 3 + B) ** 2

array([[ 81,  64],
       [900, 784]])

Array multiplication methods:

In [25]:
np.dot(A,B)

array([[  6,   6],
       [ 30, -38]])

In [26]:
A.dot(B)

array([[  6,   6],
       [ 30, -38]])

In [28]:
A @ B

array([[  6,   6],
       [ 30, -38]])