Import NumPy module:

In [1]:
import numpy as np

Create sample array:

In [8]:
A = np.random.randint(-100,100,(4,6,6))
A

array([[[-33, -12,  70, -69, -62, -34],
        [  6, -97,  98, -13, -47,  40],
        [-53, -44, -13,  50, -73, -13],
        [-34,   3,  68, -89,  94,  96],
        [  6,   3, -59,   3, -11, -69],
        [-42,  -8,  11,  53,  49,  63]],

       [[-98, -57,  33,  44,  44,  16],
        [ 78, -56,  -1,  -5,  45,  25],
        [ 61,  50, -69, -97, -93,  65],
        [ 87,   3, -42, -48,  83,  81],
        [-13, -47, -86,  55,  82,  48],
        [-99,  77,  84,  76,  19, -25]],

       [[ 74,   9, -60,  17, -48, -80],
        [ 58, -71,  14, -52,  72,  -9],
        [-22, -18, -16,  93,  52, -48],
        [-29, -68,  66,  37,  86,  14],
        [ 76,  46, -92,  21,   3, -29],
        [ -9,  86, -24, -78, -73, -96]],

       [[ 33, -24, -51,  44,   1, -24],
        [-26, -51,   2, -57,  25, -50],
        [ 97,  24,   3,  40,   8,   8],
        [-91,  23,  27,  56,  23,  16],
        [ 51, -89,  49,  -7, -11,  77],
        [-66,  42, -73, -52,  48,  69]]])

# Iterating through array:

Print all tables in array with its number:


In [12]:
number = 0
for table in A:
    number +=1
    print(f"Table number: {number}")
    print(table,end='\n\n')

Table number: 1
[[-33 -12  70 -69 -62 -34]
 [  6 -97  98 -13 -47  40]
 [-53 -44 -13  50 -73 -13]
 [-34   3  68 -89  94  96]
 [  6   3 -59   3 -11 -69]
 [-42  -8  11  53  49  63]]

Table number: 2
[[-98 -57  33  44  44  16]
 [ 78 -56  -1  -5  45  25]
 [ 61  50 -69 -97 -93  65]
 [ 87   3 -42 -48  83  81]
 [-13 -47 -86  55  82  48]
 [-99  77  84  76  19 -25]]

Table number: 3
[[ 74   9 -60  17 -48 -80]
 [ 58 -71  14 -52  72  -9]
 [-22 -18 -16  93  52 -48]
 [-29 -68  66  37  86  14]
 [ 76  46 -92  21   3 -29]
 [ -9  86 -24 -78 -73 -96]]

Table number: 4
[[ 33 -24 -51  44   1 -24]
 [-26 -51   2 -57  25 -50]
 [ 97  24   3  40   8   8]
 [-91  23  27  56  23  16]
 [ 51 -89  49  -7 -11  77]
 [-66  42 -73 -52  48  69]]



Print all third rows in array:

In [13]:
number = 0
for table in A:
    number +=1
    print(f"Table number: {number}, Row number: 3")
    print(table[2],end='\n\n')

Table number: 1, Row number: 3
[-53 -44 -13  50 -73 -13]

Table number: 2, Row number: 3
[ 61  50 -69 -97 -93  65]

Table number: 3, Row number: 3
[-22 -18 -16  93  52 -48]

Table number: 4, Row number: 3
[97 24  3 40  8  8]



Print all third columns in array:

In [14]:
number = 0
for table in A:
    number +=1
    print(f"Table number: {number}, Column number: 3")
    print(table[:,2],end='\n\n')

Table number: 1, Column number: 3
[ 70  98 -13  68 -59  11]

Table number: 2, Column number: 3
[ 33  -1 -69 -42 -86  84]

Table number: 3, Column number: 3
[-60  14 -16  66 -92 -24]

Table number: 4, Column number: 3
[-51   2   3  27  49 -73]



Print value at row number 4 and column 2 for each table:

In [17]:
number = 0
for table in A:
    number +=1
    print(f"Table number: {number}, Row number: 4, Column number: 2")
    print(f'Value is: {table[4,2]}',end='\n\n')

Table number: 1, Row number: 4, Column number: 2
Value is: -59

Table number: 2, Row number: 4, Column number: 2
Value is: -86

Table number: 3, Row number: 4, Column number: 2
Value is: -92

Table number: 4, Row number: 4, Column number: 2
Value is: 49



Print every values with are devided by 10:

In [28]:
number = 0
for item in A.flat:
    if item % 10 == 0:
        number += 1
        print(f'{number} element with value: {item}')

1 element with value: 70
2 element with value: 40
3 element with value: 50
4 element with value: 50
5 element with value: -60
6 element with value: -80
7 element with value: -50
8 element with value: 40


# Array reshape:

Sample array:

In [30]:
A = np.random.randint(-100,100,(4,6,6))
A

array([[[ -55,  -23,   60,   78,   20,  -15],
        [ -79,   19,    5,  -20,   37,  -36],
        [  78,  -60,   51,  -72,  -90,  -22],
        [  41,   22,  -76,   66,   96,    6],
        [  -9,    6,   44,  -15,   90,  -53],
        [ -73,   72,   81,   86,   58,   40]],

       [[ -43,   39,  -35,    7,  -60,   20],
        [  66,    0,   32,  -28,  -78,   83],
        [  63,   61,  -84,   41,  -53,   -7],
        [ -19,  -41,    9,  -15,  -26,   51],
        [  90,  -70,   -2,   67,  -94,   68],
        [ -47, -100,  -83,  -26,  -37,   77]],

       [[  52,   31,  -42,    3,  -89,  -36],
        [ -74,  -10,   41,   81,  -97,  -19],
        [  83,  -67,   -5,  -15,   46,   95],
        [ -84,  -20,   -9,   25,  -82,  -26],
        [  48,   16,   56,  -66,   80,   87],
        [ -56,  -27,   37,  -75,   75,   63]],

       [[  26,  -15,  -75,   -1,  -59,   62],
        [ -36,    2,   54,   57,   81,   15],
        [  15,   32,  -77,   50,  -19,  -33],
        [  72,  -34,  -65,  

Shape of array:

In [31]:
A.shape

(4, 6, 6)

Number of elements in array:

In [37]:
A.size

144

Reshape array to 2 tabels with 12 rows and 6 columns:

In [38]:
A.reshape(2,12,6)

array([[[ -55,  -23,   60,   78,   20,  -15],
        [ -79,   19,    5,  -20,   37,  -36],
        [  78,  -60,   51,  -72,  -90,  -22],
        [  41,   22,  -76,   66,   96,    6],
        [  -9,    6,   44,  -15,   90,  -53],
        [ -73,   72,   81,   86,   58,   40],
        [ -43,   39,  -35,    7,  -60,   20],
        [  66,    0,   32,  -28,  -78,   83],
        [  63,   61,  -84,   41,  -53,   -7],
        [ -19,  -41,    9,  -15,  -26,   51],
        [  90,  -70,   -2,   67,  -94,   68],
        [ -47, -100,  -83,  -26,  -37,   77]],

       [[  52,   31,  -42,    3,  -89,  -36],
        [ -74,  -10,   41,   81,  -97,  -19],
        [  83,  -67,   -5,  -15,   46,   95],
        [ -84,  -20,   -9,   25,  -82,  -26],
        [  48,   16,   56,  -66,   80,   87],
        [ -56,  -27,   37,  -75,   75,   63],
        [  26,  -15,  -75,   -1,  -59,   62],
        [ -36,    2,   54,   57,   81,   15],
        [  15,   32,  -77,   50,  -19,  -33],
        [  72,  -34,  -65,   33,

Convert array to one dimensional array:

In [36]:
A.ravel()

array([ -55,  -23,   60,   78,   20,  -15,  -79,   19,    5,  -20,   37,
        -36,   78,  -60,   51,  -72,  -90,  -22,   41,   22,  -76,   66,
         96,    6,   -9,    6,   44,  -15,   90,  -53,  -73,   72,   81,
         86,   58,   40,  -43,   39,  -35,    7,  -60,   20,   66,    0,
         32,  -28,  -78,   83,   63,   61,  -84,   41,  -53,   -7,  -19,
        -41,    9,  -15,  -26,   51,   90,  -70,   -2,   67,  -94,   68,
        -47, -100,  -83,  -26,  -37,   77,   52,   31,  -42,    3,  -89,
        -36,  -74,  -10,   41,   81,  -97,  -19,   83,  -67,   -5,  -15,
         46,   95,  -84,  -20,   -9,   25,  -82,  -26,   48,   16,   56,
        -66,   80,   87,  -56,  -27,   37,  -75,   75,   63,   26,  -15,
        -75,   -1,  -59,   62,  -36,    2,   54,   57,   81,   15,   15,
         32,  -77,   50,  -19,  -33,   72,  -34,  -65,   33,   27,   78,
         65,  -86,   32,  -18,  -87,  -91,   -4,  -42,   15,  -15,  -17,
        -92])

Create small size array:

In [45]:
B = np.random.randint(-33,33,(2,4,3))
B

array([[[-12, -26, -27],
        [ -6,  11, -29],
        [  5,  -9,  14],
        [ 23,  -9, -26]],

       [[-24, -33, -28],
        [-28,  28,  -4],
        [  9,  22,  29],
        [ 21,  -1, -30]]])

Transpose array ( invert that row are column ):

In [46]:
B.T

array([[[-12, -24],
        [ -6, -28],
        [  5,   9],
        [ 23,  21]],

       [[-26, -33],
        [ 11,  28],
        [ -9,  22],
        [ -9,  -1]],

       [[-27, -28],
        [-29,  -4],
        [ 14,  29],
        [-26, -30]]])

# Logic masks:

Array to test logic mask:

In [51]:
L = np.arange(start = -10, stop = 10, step = 0.5).reshape(10,-1)
L

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

Mask to check where values in array are lover then 0:

In [53]:
L < 0

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

Show only values lower then 0 in array using mask:

In [55]:
L[L<0]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5])

Values between -5 and 5 by two methods:

In [59]:
L[(L>= - 5) & (L<= 5)]

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

In [60]:
L[np.bitwise_and(L >= -5,L<= 5)]

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])