# Example of Binary Clasification:

Import Libraries:

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import tensorflow as tf

Create dataset:

In [2]:
data = np.random.rand(10000,150)
labels = np.random.randint(10,size = (10000,1))

print(f'Shape of data is: {data.shape}')
print(f'Shape of labels is: {labels.shape}')

Shape of data is: (10000, 150)
Shape of labels is: (10000, 1)


First 10 labels:

In [3]:
labels[0:10]

array([[0],
       [2],
       [0],
       [4],
       [9],
       [9],
       [1],
       [2],
       [6],
       [0]])

Transform labels:

In [4]:
from tensorflow.keras.utils import to_categorical

labels = to_categorical(labels,num_classes = np.unique(labels).size)

In [5]:
labels[:3]

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

Creating and fit model:

In [6]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [7]:
model = Sequential()
model.add(Dense(units = 32,activation = 'relu',
               input_shape = (150,)))
model.add(Dense(units = 10, activation = 'softmax'))

model.compile(optimizer='rmsprop',
             loss = 'categorical_crossentropy',
             metrics = ['accuracy'])
model.fit(data,labels,batch_size = 32, epochs = 30,
         validation_split=0.2)

Epoch 1/30
250/250 [==============================] - 1s 4ms/step - loss: 2.3479 - accuracy: 0.0998 - val_loss: 2.3077 - val_accuracy: 0.1030
Epoch 2/30
250/250 [==============================] - 0s 971us/step - loss: 2.3064 - accuracy: 0.1051 - val_loss: 2.3050 - val_accuracy: 0.0990
Epoch 3/30
250/250 [==============================] - 0s 978us/step - loss: 2.3014 - accuracy: 0.1110 - val_loss: 2.3050 - val_accuracy: 0.0990
Epoch 4/30
250/250 [==============================] - 0s 971us/step - loss: 2.2973 - accuracy: 0.1190 - val_loss: 2.3068 - val_accuracy: 0.1025
Epoch 5/30
250/250 [==============================] - 0s 955us/step - loss: 2.2997 - accuracy: 0.1076 - val_loss: 2.3098 - val_accuracy: 0.0950
Epoch 6/30
250/250 [==============================] - 0s 1ms/step - loss: 2.2953 - accuracy: 0.1126 - val_loss: 2.3142 - val_accuracy: 0.0925
Epoch 7/30
250/250 [==============================] - 0s 983us/step - loss: 2.2895 - accuracy: 0.1280 - val_loss: 2.3233 - val_accuracy: 0.1

Model prediction:

In [8]:
test_data = np.random.random((10,150))
model.predict(test_data)

array([[0.06477346, 0.13823393, 0.07827655, 0.0942414 , 0.1627205 ,
        0.0649778 , 0.08944164, 0.13526438, 0.05411867, 0.11795159],
       [0.09322909, 0.10132886, 0.12094113, 0.11085437, 0.09405636,
        0.11494919, 0.06609003, 0.07738329, 0.12360779, 0.09755991],
       [0.06588955, 0.06049091, 0.13288023, 0.09716542, 0.09424546,
        0.09215257, 0.14719544, 0.14168869, 0.05564263, 0.11264905],
       [0.12368207, 0.07396173, 0.07792704, 0.12378768, 0.11884189,
        0.06130612, 0.08668667, 0.06785095, 0.14415441, 0.12180144],
       [0.11620728, 0.08879122, 0.04515128, 0.13504098, 0.11904419,
        0.1410423 , 0.09117757, 0.07444729, 0.09138212, 0.09771581],
       [0.10187653, 0.10274068, 0.09289145, 0.09087482, 0.12270129,
        0.08432733, 0.09873701, 0.0945913 , 0.10114563, 0.1101139 ],
       [0.15964487, 0.17558247, 0.09125747, 0.07154799, 0.05199504,
        0.0757632 , 0.07409249, 0.05834332, 0.11480427, 0.1269689 ],
       [0.11195675, 0.11079769, 0.0552701

Result of model prediction:

In [9]:
model.predict(test_data)[0]

array([0.06477346, 0.13823393, 0.07827655, 0.0942414 , 0.1627205 ,
       0.0649778 , 0.08944164, 0.13526438, 0.05411867, 0.11795159],
      dtype=float32)

In [11]:
np.argmax(model.predict(test_data)[0])

4