# Example of Regression with Keras:

Import Libraries:

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import tensorflow as tf

Create dataset:

In [2]:
data = np.random.random((10000,150))
labels = 50 * np.random.random(10000)

print(f'Shape of data is: {data.shape}')
print(f'Shape of labels is: {labels.shape}')

Shape of data is: (10000, 150)
Shape of labels is: (10000,)


First 10 labels:

In [3]:
labels[0:10]

array([29.05666335, 31.94426137, 28.33952357, 21.16887207,  1.32690507,
       33.60437811, 26.00525331, 32.23524376, 28.72690203,  3.26615682])

Creating and fit model:

In [4]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [5]:
model = Sequential()
model.add(Dense(units = 32,activation = 'relu',
               input_shape = (150,)))
model.add(Dense(units = 1))

model.compile(optimizer='rmsprop',
             loss = 'mse',
             metrics = ['mse'])
model.fit(data,labels,batch_size = 32, epochs = 30,
         validation_split=0.2)

Epoch 1/30
250/250 [==============================] - 2s 4ms/step - loss: 344.1326 - mse: 344.1326 - val_loss: 216.9554 - val_mse: 216.9554
Epoch 2/30
250/250 [==============================] - 0s 982us/step - loss: 214.6180 - mse: 214.6180 - val_loss: 218.0321 - val_mse: 218.0321
Epoch 3/30
250/250 [==============================] - 0s 935us/step - loss: 212.7767 - mse: 212.7767 - val_loss: 218.4678 - val_mse: 218.4678
Epoch 4/30
250/250 [==============================] - 0s 951us/step - loss: 210.8833 - mse: 210.8833 - val_loss: 218.0631 - val_mse: 218.0631
Epoch 5/30
250/250 [==============================] - 0s 951us/step - loss: 216.4298 - mse: 216.4298 - val_loss: 217.7462 - val_mse: 217.7462
Epoch 6/30
250/250 [==============================] - 0s 1ms/step - loss: 217.0080 - mse: 217.0080 - val_loss: 218.1256 - val_mse: 218.1256
Epoch 7/30
250/250 [==============================] - 0s 995us/step - loss: 213.1746 - mse: 213.1746 - val_loss: 217.6925 - val_mse: 217.6925
Epoch 8/30

Model prediction:

In [6]:
test_data = np.random.random((10,150))
model.predict(test_data)

array([[23.638546],
       [28.845291],
       [23.196854],
       [25.537605],
       [27.419882],
       [23.370705],
       [25.506483],
       [20.145544],
       [26.620975],
       [20.790365]], dtype=float32)

Result of model prediction:

In [7]:
model.predict(test_data)[0]

array([23.638546], dtype=float32)