Import libraries:

In [21]:
import sklearn 
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
import plotly.figure_factory as ff
import pandas as pd
from plotly.subplots import make_subplots

Accurancy:

In [22]:
y_true = np.random.randint(0,2,size = 20)
y_true

array([1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0])

In [23]:
y_pred = np.random.randint(0,2,size = 20)
y_pred

array([1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1])

In [24]:
from sklearn.metrics import accuracy_score
print(f'Accurancy of model is: {accuracy_score(y_true,y_pred)*100}%')

Accurancy of model is: 60.0%


Model result visualistion:

In [25]:
model_df = pd.DataFrame({'y_true':y_true,'y_pred':y_pred})
model_df

y_true  y_pred
0        1       1
1        1       0
2        1       0
3        0       1
4        1       1
5        1       0
6        1       1
7        0       1
8        0       0
9        1       0
10       1       1
11       1       1
12       0       0
13       0       0
14       0       0
15       1       1
16       0       0
17       0       0
18       1       0
19       0       1

In [26]:
result_df = model_df.sort_values(by = 'y_true')
result_df = result_df.reset_index(drop= True)
result_df['sample_nb'] = result_df.index + 1
result_df

y_true  y_pred  sample_nb
0        0       1          1
1        0       0          2
2        0       0          3
3        0       1          4
4        0       0          5
5        0       0          6
6        0       1          7
7        0       0          8
8        0       0          9
9        1       1         10
10       1       1         11
11       1       1         12
12       1       0         13
13       1       1         14
14       1       0         15
15       1       1         16
16       1       0         17
17       1       0         18
18       1       1         19
19       1       0         20

In [27]:
fig = make_subplots(rows=2, cols=1)

fig.add_trace(
    go.Scatter(x=result_df.sample_nb, y=result_df.y_true,
               mode='markers',name = 'y_true'),
    row=1, col=1
)

fig.add_trace(
    go.Scatter(x=result_df.sample_nb, y=result_df.y_pred,
               mode='markers',name = 'y_pred'),
    row=2, col=1
)

fig.update_layout(height=600, width=800, title_text="Binary classification")
fig.show()

Confusion matrix:

In [28]:
from sklearn.metrics import confusion_matrix
conf_m = confusion_matrix(y_true,y_pred)
conf_m

array([[6, 3],
       [5, 6]])

In [29]:
x = ['pred_0','pred_1']
y =  ['true_1','true_0']

# change each element of conf_m to type string for annotations
z_text = [[str(y) for y in x] for x in conf_m]

# set up figure 
fig = ff.create_annotated_heatmap(conf_m, x=x, y=y, annotation_text=z_text,
                                  colorscale='Viridis')

# add title
fig.update_layout(title_text='<i><b>Confusion matrix</b></i>',
                  #xaxis = dict(title='x'),
                  #yaxis = dict(title='x')
                 )

# add custom xaxis title
fig.add_annotation(dict(font=dict(color="black",size=14),
                        x=0.5,
                        y=-0.15,
                        showarrow=False,
                        text="Predicted value",
                        xref="paper",
                        yref="paper"))

# add custom yaxis title
fig.add_annotation(dict(font=dict(color="black",size=14),
                        x=-0.35,
                        y=0.5,
                        showarrow=False,
                        text="Real value",
                        textangle=-90,
                        xref="paper",
                        yref="paper"))

# adjust margins to make room for yaxis title
fig.update_layout(margin=dict(t=50, l=200),width = 800)

# add colorbar
fig['data'][0]['showscale'] = True
fig.show()

In [30]:
names = ['False negative','True positive','True negative','False positive']
for val,name in enumerate(names):
    print(f'Result of: {name} is: {conf_m.ravel()[val]}')

Result of: False negative is: 6
Result of: True positive is: 3
Result of: True negative is: 5
Result of: False positive is: 6


In [31]:
fn,tp,tn,fp = conf_m.ravel()

Error type I:

In [32]:
false_positive_rate = fp/(fp+tn)
false_positive_rate

0.5454545454545454

Error type II:

In [33]:
false_negative_rate = fn /(fn+ tp)
false_negative_rate

0.6666666666666666

Precission

In [34]:
precission = tp / (tp + fp)
precission

0.3333333333333333

Recall

In [35]:
recall = tp / (tp + fn)
recall

0.3333333333333333

Roc curve:

In [36]:
from sklearn.metrics import roc_curve, auc

fpr, tpr, thresholds = roc_curve(y_true, y_pred,pos_label=1)

fig = px.area(
    x=fpr, y=tpr,
    title=f'ROC Curve (AUC={auc(fpr, tpr):.4f})',
    labels=dict(x='False Positive Rate', y='True Positive Rate'),
    width=700, height=500,)
fig.add_shape(
    type='line', line=dict(dash='dash'),
    x0=0, x1=1, y0=0, y1=1 )

fig.update_yaxes(scaleanchor="x", scaleratio=1)
fig.update_xaxes(constrain='domain')
fig.show()