## Multiclass classification

In [59]:
import pandas as pd
import numpy as np
import sklearn

Generate data:

In [60]:
y_true = np.random.randint(0,3,30)
y_true

array([2, 0, 0, 1, 2, 2, 1, 2, 2, 2, 2, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2, 1,
       0, 1, 2, 1, 1, 0, 1, 2])

In [61]:
y_pred = np.random.randint(0,3,30)
y_pred

array([2, 0, 1, 0, 2, 2, 1, 2, 2, 1, 0, 1, 2, 0, 2, 0, 2, 1, 0, 2, 1, 2,
       2, 2, 1, 2, 1, 2, 2, 0])

Compute accurancy:

In [62]:
from sklearn.metrics import accuracy_score
accuracy_score(y_true,y_pred)

0.4

Confusion matrix:

In [64]:
from sklearn.metrics import confusion_matrix
conf_m = confusion_matrix(y_true,y_pred)
conf_m

array([[3, 1, 4],
       [1, 2, 4],
       [3, 5, 7]])

In [84]:
import plotly.figure_factory as ff

# CHANGE 
#conf_m = ...
x = ['pred_' + str(n) for n in range(conf_m.ndim+1)]
y =  ['true_' + str(n) for n in range(conf_m.ndim,-1,-1)]

# change each element of z to type string for annotations
z_text = [[str(y) for y in x] for x in conf_m]

# set up figure 
fig = ff.create_annotated_heatmap(conf_m,
                                  x=x,
                                  y=y,
                                  annotation_text=z_text,
                                  colorscale='Viridis')

# add title
fig.update_layout(title_text='<i><b>Confusion matrix</b></i>',
                  #xaxis = dict(title='x'),
                  #yaxis = dict(title='x')
                 )

# add custom xaxis title
fig.add_annotation(dict(font=dict(color="black",size=14),
                        x=0.5,
                        y=-0.15,
                        showarrow=False,
                        text="Predicted value",
                        xref="paper",
                        yref="paper"))

# add custom yaxis title
fig.add_annotation(dict(font=dict(color="black",size=14),
                        x=-0.35,
                        y=0.5,
                        showarrow=False,
                        text="Real value",
                        textangle=-90,
                        xref="paper",
                        yref="paper"))

# adjust margins to make room for yaxis title
fig.update_layout(margin=dict(t=50, l=200))

# add colorbar
fig['data'][0]['showscale'] = True
fig.show()

Clssification raport

In [87]:
from sklearn.metrics import classification_report
print(classification_report(y_true,y_pred))

              precision    recall  f1-score   support

           0       0.43      0.38      0.40         8
           1       0.25      0.29      0.27         7
           2       0.47      0.47      0.47        15

    accuracy                           0.40        30
   macro avg       0.38      0.38      0.38        30
weighted avg       0.41      0.40      0.40        30



ROC curve:

In [89]:
from sklearn.metrics import roc_curve, auc
import plotly.express as px

fpr, tpr, thresholds = roc_curve(y_true, y_pred,pos_label=1)

fig = px.area(
    x=fpr, y=tpr,
    title=f'ROC Curve (AUC={auc(fpr, tpr):.4f})',
    labels=dict(x='False Positive Rate', y='True Positive Rate'),
    width=700, height=500,)
fig.add_shape(
    type='line', line=dict(dash='dash'),
    x0=0, x1=1, y0=0, y1=1 )

fig.update_yaxes(scaleanchor="x", scaleratio=1)
fig.update_xaxes(constrain='domain')
fig.show()