### <a name='0'></a>Import libraries

In [1]:
import numpy as np

np.__version__

'1.19.2'

### <a name='1'></a> Exercise 1
Check if all elements in table $A, B, C$ and $D$ return logistic value _True_.



```
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])
```

In [2]:
# Defining elements
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])

# Result
print(f'Array A return value: {A.all()}')
print(f'Array B return value: {B.all()}')
print(f'Array C return value: {C.all()}')
print(f'Array D return value: {D.all()}')

Array A return value: True
Array B return value: False
Array C return value: False
Array D return value: True


### <a name='2'></a> Exercise 2
Check if all elements in array $A, B$ and $C$ return logistic value _True_ axis with index 1.


```
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])
```

In [3]:
# Defining elements
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

#Result
print(f'Array A return value: {A.all(axis = 1)}')
print(f'Array B return value: {B.all(axis = 1)}')
print(f'Array C return value: {C.all(axis = 1)}')

Array A return value: [ True  True]
Array B return value: [ True False]
Array C return value: [False  True]


### <a name='3'></a> Exercise 3
Check if any element in array $A, B, C$ and $D$ return value _True_.


```
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])
```

In [4]:
# Declaration of elements
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])


# Solution
for name, array in zip(['A','B','C','D'],[A,B,C,D]):
    print(f'Array {name.upper()} return value: {array.any()}')

Array A return value: False
Array B return value: True
Array C return value: True
Array D return value: True


### <a name='4'></a> Exercise 4
Check if any element in array $A, B, C$ and $D$ return logistic value _True_ through each axis indexed 0.


```
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])
```

In [5]:
# Array declatation
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

# Result
for array_name, array in zip(['A','B','C','D'],[A,B,C,D]):
    print(f'Array {array_name} returns value {array.any(axis = 0)}')

Array A returns value [False False False]
Array B returns value [False  True False]
Array C returns value [ True False False]
Array D returns value [ True False]


### <a name='5'></a> Exercise 5
Check the array $A$ if consist numpy nan values.


```
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])
```

In [6]:
# Array declaration
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])

# Result
print('Array A consist of nan values') if np.isnan(A).all() == False else print('Array havn\'t nan values')

Array A consist of nan values


### <a name='6'></a> Exercise 6
Check if arrays $A$ oraz $B$ are similar to self with default tolerance level.


```
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])
```


In [7]:
# Arrays declaration
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])

# Result
for element_nb in range(len(A)):
    print(f'Elements on column {element_nb} are {"equal" if np.isclose(A,B)[element_nb] == True else "not equal"}')
    
print('\nElements in arrays are equal' if np.isclose(A,B).all()== True else 'Elements in arrays are not equal')

Elements on column 0 are equal
Elements on column 1 are equal
Elements on column 2 are equal

Elements in arrays are equal


### <a name='7'></a> Ćwiczenie 7
Check if arrays $A$ and $B$ are equal.


```
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])
```

In [8]:
# Assign array
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])

# Result
Compare_array = A==B
for element_number in range(len(A)):
    print(f'Elements in {element_number} column are {"Equal" if Compare_array[element_number] == True else "Not equal"}')
    
print('\n')
print('Elements in arrays are equal' if Compare_array.all()== True else 'Elements in arrays are not equal')

Elements in 0 column are Not equal
Elements in 1 column are Not equal
Elements in 2 column are Equal


Elements in arrays are not equal


### <a name='8'></a> Ćwiczenie 8
Check if array $A$ has greater values than array $B$.


```
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])
```



In [9]:
# Enter arrays
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])

result_array = A>B
for number,value in enumerate(result_array):
    if value == True:
        print(f'Element number {number} in array A is greather then in array B')
    else:
        print(f'Element number {number} in array A is not greather then in array B')

Element number 0 in array A is greather then in array B
Element number 1 in array A is not greather then in array B
Element number 2 in array A is not greather then in array B
Element number 3 in array A is not greather then in array B


### <a name='9'></a> Exercise 9
Create array of shape _4x4_ filled by zeros. Set data types to _int_.

__Excepted result:__


```
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])
```

In [10]:
# Result
np.zeros(shape = (4,4),dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### <a name='10'></a> Exercise 10
Create numpy array shape of _10x10_ filled by values 255. Set data type to _float_.

__Excepted result:__


```
array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])
```

In [11]:
# Result
np.full(shape = (10,10),fill_value=255,dtype=float)

array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])