### <a name='0'></a>Import libraries

In [1]:
import numpy as np

np.__version__

'1.19.2'

### <a name='1'></a> Exercise 21
Generate table below. Save the table to file: _'array.npy'_ and then load the file to another variable.


```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```

In [2]:
# Create table
table = np.arange(0,12,1,dtype ='int').reshape(3,4)

# Save table to file
np.save('array.npy', table, allow_pickle=True, fix_imports=True)

# Load table from file
Load_arr = np.load('array.npy', mmap_mode=None, allow_pickle=True, fix_imports=True, encoding='ASCII')
Load_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### <a name='2'></a> Exercise 22
Generate table as below:


```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```


Then save the table to file _'array.txt'_ with two letter precision after dot.Then load table to another variable.

In [3]:
# Create table
table = np.arange(0,12,1,dtype ='int').reshape(3,4)

# Save table to file
np.savetxt('array.txt', table, fmt='%.2f', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)

# Load, save and print the variable
load_arr = np.loadtxt('array.txt', comments='#', delimiter=' '
              , converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding=None, max_rows=None)
load_arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

### <a name='3'></a> Exercise 23
Generate table as below. Then convert the table to list.

```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```

In [4]:
# Solution
table = np.arange(0,12,1,dtype ='int').reshape(3,4)
table.tolist()

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]

### <a name='4'></a> Exercise 24
Array is given:

```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```
Using cutting operator transform table to form below:

```
array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])
```







In [5]:
# Solution
table = np.arange(0,12,1,dtype ='int').reshape(3,4)
table[::-1]

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

* Column change (inverted order)


```
array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])
```


In [6]:
# Solution
table[:,::-1]


array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])

* Change the rows and columns order to inverted:


```
array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])
```       

In [7]:
# Solution
table[::-1,::-1]

array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

### <a name='5'></a> Exercise 25
Load the table as below:

```
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])
```
Transform above table to table below:


```
array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])
```

In [9]:
# Solution
table = np.ones((4,4))
result = np.zeros((6,6))
np.zeros((6,6))[1:-1,1:-1]  = np.ones((4,4))
result

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
# Alternative solution
np.pad(table, pad_width=1, constant_values=0)

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

### <a name='6'></a> Exercise 26
The table is given:

```
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])
```
Transform the table to:


```
array([[10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0]])
```

In [11]:
# Solution
zeros = np.zeros((6,6),dtype = 'int')
zeros[::2,::2] = 10
zeros[1::2,0::2] = 5
zeros

array([[10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0]])

### <a name='7'></a> Exercise 27
Connect tables $A$ na $B$ to one.


```
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])
```

__Excepted result:__


```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 4,  3,  7,  2],
       [ 0,  5,  2,  6]])
```

In [12]:
# Assign variable
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])

# Solution
np.concatenate((A,B))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 4,  3,  7,  2],
       [ 0,  5,  2,  6]])

In [13]:
# Alternative solution
np.append(A,B,axis = 0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 4,  3,  7,  2],
       [ 0,  5,  2,  6]])

### <a name='8'></a> Exercise 28
From tables $A$ and $B$ choice the same elements.

```
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])      
```

In [14]:
# Defining arrays
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]]) 

# Solution
np.intersect1d(A, B, assume_unique=False, return_indices=False)

array([0, 2, 3])

### <a name='9'></a> Exercise 29
Find unique values form table $A$.

```
A = np.array([[5, 1, 2, 1, 2],
              [9, 1, 9, 7, 5],
              [4, 1, 5, 7, 9]])
```

In [15]:
# Table definition
A = np.array([[5, 1, 2, 1, 2],
              [9, 1, 9, 7, 5],
              [4, 1, 5, 7, 9]])

# Solution
np.unique(A)

array([1, 2, 4, 5, 7, 9])

### <a name='10'></a> Exercise 30
From table:


```
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])
```



Return indexes of max value from each rows.

In [16]:
# Array
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])

# Solution
A.argmax(axis =1)

array([0, 2, 1], dtype=int64)