## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Exercise 51](#1)
* [Exercise 52](#2)
* [Exercise 53](#3)
* [Exercise 54](#4)
* [Exercise 55](#5)
* [Exercise 56](#6)
* [Exercise 57](#7)
* [Exercise 58](#8)
* [Exercise 59](#9)
* [Exercise 60](#10)

## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Exercise 51](#1)
* [Exercise 52](#2)
* [Exercise 53](#3)
* [Exercise 54](#4)
* [Exercise 55](#5)
* [Exercise 56](#6)
* [Exercise 57](#7)
* [Exercise 58](#8)
* [Exercise 59](#9)
* [Exercise 60](#10)

## Numpy

### Spis treści:
*[Import biblioteki](#0)* [Exercise 51](#1)
*[Exercise 52](#2)* [Exercise 53](#3)
*[Exercise 54](#4)* [Exercise 55](#5)
*[Exercise 56](#6)* [Exercise 57](#7)
*[Exercise 58](#8)* [Exercise 59](#9)
* [Exercise 60](#10)

## Numpy

### Spis treści:
*[Import biblioteki](#0)* [Exercise 51](#1)
*[Exercise 52](#2)* [Exercise 53](#3)
*[Exercise 54](#4)* [Exercise 55](#5)
*[Exercise 56](#6)* [Exercise 57](#7)
*[Exercise 58](#8)* [Exercise 59](#9)
* [Exercise 60](#10)

## Numpy

### Table of Contents:
*[Library import] (# 0)* [Exercise 51] (# 1)
*[Exercise 52] (# 2)* [Exercise 53] (# 3)
*[Exercise 54] (# 4)* [Exercise 55] (# 5)
*[Exercise 56] (# 6)* [Exercise 57] (# 7)
*[Exercise 58] (# 8)* [Exercise 59] (# 9)
* [Exercise 60] (# 10)

## Numpy

### Table of Contents:
*[Library import] (# 0)* [Exercise 51] (# 1)
*[Exercise 52] (# 2)* [Exercise 53] (# 3)
*[Exercise 54] (# 4)* [Exercise 55] (# 5)
*[Exercise 56] (# 6)* [Exercise 57] (# 7)
*[Exercise 58] (# 8)* [Exercise 59] (# 9)
* [Exercise 60] (# 10)

### <a name='0'></a>Import libraries

In [1]:
import numpy as np

np.random.seed(42)
np.__version__

'1.19.2'

### <a name='1'></a> Exercise 51
Two table are given $A$ i $B$:


```
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
```
* Connect table to recive table as showed below:


```
array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])
```

In [2]:
# Array assagin
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])

# Solution

np.concatenate((A,B))

array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])

* Connect table A and B in way showed below:


```
array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])
```

In [3]:
# Solution
np.concatenate((A,B),axis = 1)

array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])

### <a name='2'></a> Exercise 52
Connect table _data_ and table _target_:

```
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
```



Connect table to recive result:


```
array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])
```



In [4]:
# Array assign
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
# Solution
np.concatenate((data,target),axis = 1)

array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])

### <a name='3'></a> Exercise 53
Three the same dimensional arrays are given:  


```
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
```
Transform each array to to achieve result.

__Expected result:__


```
array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])
```

In [5]:
# Create table
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])

# Solution

np.concatenate((feature1.reshape(-1,1),feature2.reshape(-1,1),feature3.reshape(-1,1)), axis = 1)

array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])

### <a name='4'></a> Exercise 54
Table is given:

```
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A
```
```
array([[0, 0, 4, 6, 2, 4, 1, 1],
       [0, 0, 6, 2, 2, 4, 1, 1],
       [0, 0, 1, 3, 5, 5, 1, 1],
       [0, 0, 3, 1, 5, 4, 1, 1],
       [0, 0, 2, 6, 1, 3, 1, 1]])
```

Devide table to recive table $A1$ with two first columns, table $A2$ with four next columns and last 2 columns make table $A3$.

In [6]:
# Create array
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1

# Solution
A1 = A[:,:2]
print(A1)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [7]:
# Solution
A2 = A[:,2:6]
print(A2)

[[4 6 2 4]
 [6 2 2 4]
 [1 3 5 5]
 [3 1 5 4]
 [2 6 1 3]]


In [8]:
# Solution
A3 = A[:,-2:]
print(A3)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


### <a name='5'></a> Exercise 55
Table $A$ is generated:

```
A = np.random.randint(low=0, high=2, size=(10, 6))
```
Return number of not null elements.

In [9]:
# Create array
A = np.random.randint(low=0, high=2, size=(10, 6))

# Solution
np.count_nonzero(A)

38

Return number of not null elements in rows.

In [10]:
# Solution
np.count_nonzero(A,axis = 1)

array([4, 2, 1, 5, 4, 3, 3, 6, 4, 6], dtype=int64)

### <a name='6'></a> Exercise 56
Random table is given $A$:

```
A = np.random.randn(10, 4)
```

```
array([[-0.53441645, -1.49505387, -0.78925833,  0.74371128],
       [-0.21216142, -0.42686879,  0.50144833,  1.15818665],
       [ 0.25711687,  0.3145129 ,  1.37186213,  0.17555329],
       [-0.30928855,  0.6731255 , -0.25663018, -0.36782572],
       [ 1.27373362, -0.29195267, -2.65517605,  0.34551794],
       [-0.39551645, -0.28913686,  0.45293633, -0.16606091],
       [ 0.21493883, -2.02231493, -0.94305681,  1.40395874],
       [-0.0185508 , -1.67350462, -1.07253183, -0.99258618],
       [ 0.10234768, -0.43260928, -0.6591823 ,  0.0039373 ],
       [ 0.4777541 , -0.25902864, -0.57470921, -0.42149822]])
```


Set printing precision to 4 digits after dot and print table $A$.

In [11]:
# Table assign 
A = np.random.randn(10, 4)

# Solution
np.set_printoptions(precision= 4)
A

array([[ 0.7385,  0.1714, -0.1156, -0.3011],
       [-1.4785, -0.7198, -0.4606,  1.0571],
       [ 0.3436, -1.763 ,  0.3241, -0.3851],
       [-0.6769,  0.6117,  1.031 ,  0.9313],
       [-0.8392, -0.3092,  0.3313,  0.9755],
       [-0.4792, -0.1857, -1.1063, -1.1962],
       [ 0.8125,  1.3562, -0.072 ,  1.0035],
       [ 0.3616, -0.6451,  0.3614,  1.538 ],
       [-0.0358,  1.5646, -2.6197,  0.8219],
       [ 0.087 , -0.299 ,  0.0918, -1.9876]])

### <a name='7'></a> Exercise 57
Table $A$ is given:

```
A = np.array([1.2e-6, 1.7e-7])
```

Set printing precision to 8 numbers then remove e notation from matrix. Print table $A$.

__Excepted value:__


```
array([0.0000012 , 0.00000017])
```





In [12]:
A = np.array([1.2e-6, 1.7e-7])

# Solution
np.set_printoptions(precision= 8,suppress = True)
A

array([0.0000012 , 0.00000017])

### <a name='8'></a> Exercise 58
The table $A$ is given:

```
A = np.random.randn(8, 4)
```
Remove third column from table $A$.

__Excepted_result:__


```
array([[-0.55692881, -0.66003196,  0.70856031],
       [ 0.22378737, -0.19796576, -0.16889332],
       [ 0.26062786,  0.29865445, -0.92259267],
       [-2.40317659,  1.79961876, -1.96495796],
       [ 0.13051561, -1.7085185 ,  0.54885043],
       [ 1.77268727,  0.38751181, -0.05141955],
       [-1.80858596, -0.45075211,  0.15332866],
       [ 1.94218961, -1.93679529, -1.83350954]])
```

In [13]:
A = np.random.randn(8, 4)
# Solution
np.delete(A, 2, axis=1)

array([[-0.21967189,  0.35711257, -0.51827022],
       [-0.8084936 , -0.50175704,  0.32875111],
       [-0.5297602 ,  0.51326743,  0.96864499],
       [-0.70205309, -0.32766215, -1.46351495],
       [ 0.29612028,  0.26105527, -0.23458713],
       [-1.41537074, -0.42064532, -0.80227727],
       [-0.16128571,  0.40405086,  0.17457781],
       [ 0.25755039, -0.07444592, -0.02651388]])

### <a name='9'></a> Exercise 59
The table $v$ as vector is given:

```
v = np.array([3, 4, -2])
```
Calculate norm of $v$.


In [14]:
v = np.array([3, 4, -2])
# Solution
np.linalg.norm(v)

5.385164807134504

### <a name='10'></a> Exercise 60
The table $A$ is given as example:


```
A = np.random.randint(10, size=(100, 30))
```
Set numpy option to return ten extreme elements from the table. Print table $A$.


In [15]:
A = np.random.randint(10, size=(100, 30))
# Solution
np.set_printoptions(edgeitems=10)
A

array([[0, 7, 0, 0, 1, 1, 5, 6, 4, 0, ..., 0, 5, 7, 4, 3, 1, 5, 5, 0, 8],
       [5, 2, 3, 3, 2, 9, 2, 2, 3, 6, ..., 1, 6, 9, 2, 6, 9, 8, 3, 0, 1],
       [0, 4, 4, 6, 8, 8, 2, 2, 2, 3, ..., 7, 3, 2, 8, 2, 8, 1, 1, 1, 5],
       [2, 8, 3, 0, 3, 0, 4, 3, 7, 7, ..., 2, 5, 7, 1, 4, 0, 0, 4, 2, 3],
       [2, 0, 0, 4, 5, 2, 8, 4, 7, 0, ..., 9, 5, 9, 2, 7, 7, 1, 5, 6, 1],
       [9, 1, 9, 0, 7, 0, 8, 5, 6, 9, ..., 3, 0, 7, 2, 6, 1, 1, 6, 5, 2],
       [8, 9, 5, 9, 9, 5, 0, 3, 9, 5, ..., 2, 6, 7, 3, 1, 9, 2, 0, 7, 2],
       [9, 6, 9, 4, 9, 4, 6, 8, 4, 0, ..., 4, 5, 6, 2, 9, 2, 4, 5, 8, 4],
       [0, 3, 4, 9, 9, 4, 6, 3, 0, 4, ..., 2, 9, 0, 7, 4, 3, 7, 6, 1, 0],
       [3, 7, 1, 2, 0, 0, 2, 4, 2, 0, ..., 7, 9, 9, 9, 1, 2, 8, 6, 3, 9],
       ...,
       [6, 3, 5, 2, 5, 1, 7, 1, 6, 8, ..., 9, 7, 2, 9, 0, 8, 0, 2, 7, 2],
       [3, 7, 0, 5, 0, 0, 7, 3, 0, 9, ..., 0, 8, 0, 7, 4, 2, 6, 6, 8, 6],
       [2, 0, 7, 2, 7, 7, 4, 0, 9, 6, ..., 1, 3, 0, 3, 1, 4, 2, 7, 3, 0],
       [0, 9, 2, 8, 6, 1, 

# enter your solution here