### <a name='0'></a>Import libraries

In [1]:
import numpy as np

np.set_printoptions(suppress=True, precision=4)
np.random.seed(42)
np.__version__

'1.19.2'

### <a name='1'></a> Exercise 61
Tables $A$ i $B$ are given:

```
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
```

Create table with aritmetic mean from each element of table $A$ and $B$ .

__Excepted result:__


```
array([[3.5, 3.5, 5.5, 3.5],
       [5.5, 3. , 1.5, 5.5]])
```

In [2]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])

# Solution
np.mean( np.array([ A, B ]), axis=0 )

array([[3.5, 3.5, 5.5, 3.5],
       [5.5, 3. , 1.5, 5.5]])

### <a name='2'></a> Exercise 62
Two tables $A$ and $B$ are given: 

```
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
```
Multyply each element of tables.

In [3]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])

# Solution
np.multiply(A,B)

array([[12, 12, 18, 10],
       [30,  9,  2, 30]])

### <a name='3'></a> Exercise 63
Table $A$ is given:

```
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
```
Calculate square root of each element from table $A$.

In [4]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
# Solution
np.sqrt(A)

array([[1.7321, 2.    , 3.    , 1.4142],
       [2.2361, 1.7321, 1.4142, 2.2361]])

### <a name='4'></a> Exercise 64
Tables $A$ and $B$ are given:


```
A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')
```
Check arithmetic one function on table $A$ and then compare result to table $B$.
__Arithmetic one:__ For any degree $\alpha \in R$ makes:
$$sin^2\alpha + cos^2\alpha = 1$$



In [5]:
A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')
# Solution
A = np.power(np.sin(A),2) + np.power(np.cos(A),2)
print(f' Whitout tolerance the result is {np.equal(A,B).all()}')

 Whitout tolerance the result is False


In [6]:
A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')
# Solution
print(f'With tolerance the result is: '
      f'{np.allclose(np.power(np.sin(A),2) + np.power(np.cos(A),2),B)}')

With tolerance the result is: True


### <a name='5'></a> Exercise 65

Two tables $A$ and $B$ are given.  
$A$ - array of shape $(3, 2)$  
$B$ - array of shape $(2, 3)$

```
A = np.array([[2, 3],
              [-4, 2],
              [5, 0]])
B = np.array([[4, 3, 2],
              [-1, 0, 2]])
```
Make arrays multiply $A$ i $B$.

In [7]:
A = np.array([[2, 3],
              [-4, 2],
              [5, 0]])
B = np.array([[4, 3, 2],
              [-1, 0, 2]])
# Solution
A @ B

array([[  5,   6,  10],
       [-18, -12,  -4],
       [ 20,  15,  10]])

### <a name='6'></a> Exercise 66
The table $A$ of shape $(x,x)$ is given:

```
A = np.array([[-2, 0, 4],
              [5, 2, -1],
              [-4, 2, 4]])
```
Compute the determinant of array $A$.

In [8]:
A = np.array([[-2, 0, 4],
              [5, 2, -1],
              [-4, 2, 4]])
# Solution
np.linalg.det(A)

51.999999999999986

### <a name='7'></a> Exercise 67
The square shape table named $A$ is given:

```
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
```
Compute the eigenvalues and right eigenvectors of a square array $A$.

In [9]:
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
# Solution
eigenvalues,eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[-9.2462 -3.      7.2462]
[[-0.6262 -0.8944  0.8902]
 [-0.3131  0.      0.4451]
 [ 0.7141  0.4472 -0.0976]]


### <a name='8'></a> Exercise 68
The table of square size and name $A$ is given:

```
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
```
Calculate inverted array to $A$.


In [10]:
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])

# Solution
np.linalg.inv(A)

array([[-0.2139,  0.7562,  0.2388],
       [ 0.0597,  0.0448,  0.1194],
       [ 0.0995, -0.2587, -0.1343]])

### <a name='9'></a> Exercise 69
The table of square size and name $A$ is given:

```
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
```
Compute the trace of array $A$.


In [11]:
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
# Solution
np.trace(A)

-5

### Exercise 69 B
Transpose the $A$.

In [12]:
# Solution
np.transpose(A)

array([[  5,   4,  -4],
       [  8,   1,   4],
       [ 16,   8, -11]])

### <a name='10'></a> Exercise 70
There are two tables $A$ and $B$:   
$A$ - is shape of $(4, 2)$  
$B$ - is shape of $(1, 8)$

```
A = np.array([[2, 0],
              [4, 2],
              [5, 3],
              [4, 2]])
B = np.array([[4, 0, 2, 1, 1, 0, 2, 9]])
```
Transform table $B$ and make array multyply $A \cdot B$. Return result.

__Excepted result:__


```
array([[ 8,  0,  4,  2],
       [18,  0, 12, 22],
       [23,  0, 16, 32],
       [18,  0, 12, 22]])
```




In [13]:
A = np.array([[2, 0],
              [4, 2],
              [5, 3],
              [4, 2]])
B = np.array([[4, 0, 2, 1, 1, 0, 2, 9]])

# Solution
print(f'Shape of array A is: {A.shape}')
print(f'Shape of array B is: {B.shape}')

if A.shape[1] != B.shape[0]:
    print('Shape B needs reshaping')
    B = B.reshape(A.shape[1],-1)
    print(f'After reshape array B is: {B.shape}')
    
A@B

Shape of array A is: (4, 2)
Shape of array B is: (1, 8)
Shape B needs reshaping
After reshape array B is: (2, 4)


array([[ 8,  0,  4,  2],
       [18,  0, 12, 22],
       [23,  0, 16, 32],
       [18,  0, 12, 22]])