### <a name='0'></a>Import libraries

In [1]:
import numpy as np

np.random.seed(42)
np.__version__

'1.19.2'

### <a name='1'></a> Exercise 71
Table $A$ is given:

```
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])
```
Shuffle randomly table $A$ starting form second row.

In [2]:
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])
# Solution
np.random.shuffle(A[1:])
A

array([['id', 'price'],
       ['002', '4.99'],
       ['005', '1.49'],
       ['003', '7.99'],
       ['001', '14.99'],
       ['004', '2.49']], dtype='<U5')

### <a name='2'></a> Exercise 72
The table $A$ is given:

```
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])
```
Return table of indexes sorted ascending by values in table $A$.

__Expected result:__


```
array([5, 2, 1, 0, 4, 3])
```


In [3]:
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])
# Solution
np.argsort(A)

array([5, 2, 1, 0, 4, 3], dtype=int64)

### <a name='3'></a> Exercise 73
The table $A$ is given:

```
A = np.random.randn(10, 8)
```

Round values from table A to 3 decimal number.

In [4]:
A = np.random.randn(10, 8)
# Solution
np.round(A,3)

array([[ 0.474,  1.368, -0.917, -0.124, -2.011, -0.493,  0.393, -0.929],
       [ 0.08 , -0.16 ,  0.022, -0.428, -0.532, -0.117,  0.222, -0.768],
       [ 0.142, -0.035,  1.134, -0.105, -0.525,  1.913, -2.027,  1.119],
       [ 0.779, -1.101,  1.13 ,  0.373, -0.386, -1.159,  0.566, -0.704],
       [-1.378, -0.353, -0.461,  0.067, -0.176,  1.201,  0.698, -0.172],
       [-0.907,  1.189,  0.786,  2.656,  0.263,  1.642,  0.461,  0.086],
       [-1.51 ,  0.722, -0.843, -0.513, -0.044, -0.275, -1.563, -0.796],
       [ 0.931,  0.678,  0.698,  0.174,  0.662,  0.241, -0.168,  1.165],
       [-0.246, -0.77 ,  1.212,  1.233, -1.574,  0.638, -2.044,  1.069],
       [-0.934,  0.784, -0.615,  0.333, -1.381, -0.281, -0.06 ,  0.961]])

### <a name='4'></a> Exercise 74
Find the roots of the polynomial:
* $W(x) = 4x^2 + 5x + 1$

In [5]:
# Solution
result = np.roots([4,5,1])
result

array([-1.  , -0.25])

Check.

In [6]:
# Solution
for element in result:
    if 4 * element **2 + 5* element +1 == 0:
        print(f'For element {element} root is true')

For element -1.0 root is true
For element -0.25 root is true


### <a name='5'></a> Exercise 75
Find the roots of the polynomial:
* $Q(x) = 2x^3 + 4x^2 -5x + 1$
* $R(x) = 2x^3 -5x + 1$


In [7]:
# Solution
Q = np.array([2,4,-5,1])
result_of_Q = np.roots(Q)
print(f'Roots of Q polynominal are: {result_of_Q}')

P = np.array([2,0,-5,1])
result_of_P = np.roots(P)
print(f'Roots of P polynominal are: {result_of_P}')

Roots of Q polynominal are: [-2.91610583  0.65388685  0.26221898]
Roots of P polynominal are: [-1.67298165  1.46961743  0.20336421]


### <a name='6'></a> Exercise 76
Polynomials are given:

* $W(x) = 4x^2 + 5x + 1$
* $Q(x) = 2x^3 + 4x^2 -5x + 1$


In [8]:
W = np.array([4, 5, 1])
Q = np.array([2, 4, -5, 1])

Make:
* $W(x) + Q(x)$

In [9]:
# Solution
np.polyadd(W,Q)

array([2, 8, 0, 2])

* $W(x) - Q(x)$


In [10]:
# Solution
np.polysub(W,Q)

array([-2,  0, 10,  0])

* $W(x) * Q(x)$


In [11]:
# Solution
np.polymul(W,Q)

array([  8,  26,   2, -17,   0,   1])

* $W(x) + 2Q(x)$

In [12]:
# Solution
np.polyadd(W,2*Q)

array([ 4, 12, -5,  3])

### <a name='7'></a> Exercise 77
Table is given:

```
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])
```

Use function (_sign function_) on table $A$. Dla przypomnienia funkcja działa nastpująco: dla wartości ujemnych zwraca -1, dla zera wartość zero, dla wartości dodatnich 1.

__Excepted result:__


```
array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])
```

In [13]:
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])
# Solution
np.sign(A)

array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])

### <a name='8'></a> Exercise 78
Using function _np.arange()_ generate table as showed below:


```
array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31'], dtype='datetime64[D]')
```



In [14]:
# Solution
np.arange(np.datetime64('2021-01-01'), np.datetime64('2021-02-01'),dtype='datetime64')

array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31'], dtype='datetime64[D]')


### <a name='9'></a> Exercise 79

Using function _np.arange()_ Generate table as below:



```
array([['2021-01', '2021-02', '2021-03'],
       ['2021-04', '2021-05', '2021-06'],
       ['2021-07', '2021-08', '2021-09'],
       ['2021-10', '2021-11', '2021-12']], dtype='datetime64[M]')
```



In [15]:
# Solution
np.arange(np.datetime64('2021-01'), np.datetime64('2022-01'),dtype='datetime64').reshape(4,-1)

array([['2021-01', '2021-02', '2021-03'],
       ['2021-04', '2021-05', '2021-06'],
       ['2021-07', '2021-08', '2021-09'],
       ['2021-10', '2021-11', '2021-12']], dtype='datetime64[M]')

### <a name='10'></a> Exercise 80

Using function _np.datetime64()_ generate present date.

In [16]:
# Solution
np.datetime64('today') 

numpy.datetime64('2021-02-15')