### <a name='0'></a>Import libraries

In [1]:
import numpy as np

np.set_printoptions(linewidth=160, suppress=True)
np.__version__

'1.19.2'

### <a name='1'></a> Exercise 91
The string named _wig_games_raw_  is given and consist data about Polish game stocks from index WIG.GAMES:

```
wig_games_raw = """Profil	Czas	Kurs	Zmiana	Zmiana %	Odn.	Otw.	Min.	Max.	Wolumen	Obrót	Udział
11B (11BIT)	17 kwi 17:01	391.00	+8.00	(+2.09%)	383.00	383.50	383.00	394.00	12 784	4 994 874	19.034%
CDR (CDPROJEKT)	17 kwi 17:01	339.50	+5.30	(+1.59%)	334.20	338.30	337.00	344.20	233 059	79 245 368	39.618%
CIG (CIGAMES)	17 kwi 17:03	0.742	-0.012	(-1.59%)	0.754	0.772	0.730	0.772	1 311 078	971 459	1.855%
PLW (PLAYWAY)	17 kwi 17:03	387.50	+18.00	(+4.87%)	369.50	374.00	373.00	388.00	33 206	12 661 786	10.638%
TEN (TSGAMES)	17 kwi 17:02	349.50	+22.50	(+6.88%)	327.00	332.00	330.00	353.50	39 793	13 697 060	28.855%"""
```

From given string create array named _wig_games_.

__Excepted result:__


```
array([['Profil', 'Czas', 'Kurs', 'Zmiana', 'Zmiana%', 'Odn.', 'Otw.', 'Min.', 'Max.', 'Wolumen', 'Obrót', 'Udział'],
       ['11B(11BIT)', '17kwi17:01', '391.00', '+8.00', '(+2.09%)', '383.00', '383.50', '383.00', '394.00', '12784', '4994874', '19.034%'],
       ['CDR(CDPROJEKT)', '17kwi17:01', '339.50', '+5.30', '(+1.59%)', '334.20', '338.30', '337.00', '344.20', '233059', '79245368', '39.618%'],
       ['CIG(CIGAMES)', '17kwi17:03', '0.742', '-0.012', '(-1.59%)', '0.754', '0.772', '0.730', '0.772', '1311078', '971459', '1.855%'],
       ['PLW(PLAYWAY)', '17kwi17:03', '387.50', '+18.00', '(+4.87%)', '369.50', '374.00', '373.00', '388.00', '33206', '12661786', '10.638%'],
       ['TEN(TSGAMES)', '17kwi17:02', '349.50', '+22.50', '(+6.88%)', '327.00', '332.00', '330.00', '353.50', '39793', '13697060', '28.855%']], dtype='<U14')
```






In [2]:
wig_games_raw = """Profil    Czas    Kurs    Zmiana    Zmiana %    Odn.    Otw.    Min.    Max.    Wolumen    Obrót    Udział
11B (11BIT)    17 kwi 17:01    391.00    +8.00    (+2.09%)    383.00    383.50    383.00    394.00    12 784    4 994 874    19.034%
CDR (CDPROJEKT)    17 kwi 17:01    339.50    +5.30    (+1.59%)    334.20    338.30    337.00    344.20    233 059    79 245 368    39.618%
CIG (CIGAMES)    17 kwi 17:03    0.742    -0.012    (-1.59%)    0.754    0.772    0.730    0.772    1 311 078    971 459    1.855%
PLW (PLAYWAY)    17 kwi 17:03    387.50    +18.00    (+4.87%)    369.50    374.00    373.00    388.00    33 206    12 661 786    10.638%
TEN (TSGAMES)    17 kwi 17:02    349.50    +22.50    (+6.88%)    327.00    332.00    330.00    353.50    39 793    13 697 060    28.855%"""
# Solution
wig_games = np.char.splitlines(wig_games_raw)
wig_games = np.array([element.split('    ') for element in wig_games.item()])
np.char.replace(wig_games,' ','')

array([['Profil', 'Czas', 'Kurs', 'Zmiana', 'Zmiana%', 'Odn.', 'Otw.', 'Min.', 'Max.', 'Wolumen', 'Obrót', 'Udział'],
       ['11B(11BIT)', '17kwi17:01', '391.00', '+8.00', '(+2.09%)', '383.00', '383.50', '383.00', '394.00', '12784', '4994874', '19.034%'],
       ['CDR(CDPROJEKT)', '17kwi17:01', '339.50', '+5.30', '(+1.59%)', '334.20', '338.30', '337.00', '344.20', '233059', '79245368', '39.618%'],
       ['CIG(CIGAMES)', '17kwi17:03', '0.742', '-0.012', '(-1.59%)', '0.754', '0.772', '0.730', '0.772', '1311078', '971459', '1.855%'],
       ['PLW(PLAYWAY)', '17kwi17:03', '387.50', '+18.00', '(+4.87%)', '369.50', '374.00', '373.00', '388.00', '33206', '12661786', '10.638%'],
       ['TEN(TSGAMES)', '17kwi17:02', '349.50', '+22.50', '(+6.88%)', '327.00', '332.00', '330.00', '353.50', '39793', '13697060', '28.855%']], dtype='<U14')

### <a name='2'></a> Exercise 92
From table _wig_games_ remove columns:
* Zmiana
* Zmiana %
* Odn.
* Wolumen

__Excepted result:__


```
array([['Profil', 'Czas', 'Kurs', 'Otw.', 'Min.', 'Max.', 'Obrót', 'Udział'],
       ['11B (11BIT)', '17 kwi 17:01', '391.00', '383.50', '383.00', '394.00', '4 994 874', '19.034%'],
       ['CDR (CDPROJEKT)', '17 kwi 17:01', '339.50', '338.30', '337.00', '344.20', '79 245 368', '39.618%'],
       ['CIG (CIGAMES)', '17 kwi 17:03', '0.742', '0.772', '0.730', '0.772', '971 459', '1.855%'],
       ['PLW (PLAYWAY)', '17 kwi 17:03', '387.50', '374.00', '373.00', '388.00', '12 661 786', '10.638%'],
       ['TEN (TSGAMES)', '17 kwi 17:02', '349.50', '332.00', '330.00', '353.50', '13 697 060', '28.855%']], dtype='<U15')
```



In [3]:
# Solution
wig_games[:,[0,1,2,6,7,8,10,11]]

array([['Profil', 'Czas', 'Kurs', 'Otw.', 'Min.', 'Max.', 'Obrót', 'Udział'],
       ['11B (11BIT)', '17 kwi 17:01', '391.00', '383.50', '383.00', '394.00', '4 994 874', '19.034%'],
       ['CDR (CDPROJEKT)', '17 kwi 17:01', '339.50', '338.30', '337.00', '344.20', '79 245 368', '39.618%'],
       ['CIG (CIGAMES)', '17 kwi 17:03', '0.742', '0.772', '0.730', '0.772', '971 459', '1.855%'],
       ['PLW (PLAYWAY)', '17 kwi 17:03', '387.50', '374.00', '373.00', '388.00', '12 661 786', '10.638%'],
       ['TEN (TSGAMES)', '17 kwi 17:02', '349.50', '332.00', '330.00', '353.50', '13 697 060', '28.855%']], dtype='<U15')

### <a name='3'></a> Exercise 93
Table _wig_games_ save to file _wig_games.csv_.

In [4]:
# Solution
np.savetxt('wig_games.csv', wig_games, delimiter=',', fmt='%s')

### <a name='4'></a> Exercise 94
Load saved excel file to variable _wig_games_new_ .

In [5]:
# Solution
wig_games_new = np.loadtxt('wig_games.csv', delimiter=',',dtype=str)
wig_games_new

array([['Profil', 'Czas', 'Kurs', 'Zmiana', 'Zmiana %', 'Odn.', 'Otw.', 'Min.', 'Max.', 'Wolumen', 'Obrót', 'Udział'],
       ['11B (11BIT)', '17 kwi 17:01', '391.00', '+8.00', '(+2.09%)', '383.00', '383.50', '383.00', '394.00', '12 784', '4 994 874', '19.034%'],
       ['CDR (CDPROJEKT)', '17 kwi 17:01', '339.50', '+5.30', '(+1.59%)', '334.20', '338.30', '337.00', '344.20', '233 059', '79 245 368', '39.618%'],
       ['CIG (CIGAMES)', '17 kwi 17:03', '0.742', '-0.012', '(-1.59%)', '0.754', '0.772', '0.730', '0.772', '1 311 078', '971 459', '1.855%'],
       ['PLW (PLAYWAY)', '17 kwi 17:03', '387.50', '+18.00', '(+4.87%)', '369.50', '374.00', '373.00', '388.00', '33 206', '12 661 786', '10.638%'],
       ['TEN (TSGAMES)', '17 kwi 17:02', '349.50', '+22.50', '(+6.88%)', '327.00', '332.00', '330.00', '353.50', '39 793', '13 697 060', '28.855%']],
      dtype='<U15')

### <a name='5'></a> Exercise 95
The string named _playway_raw_ is given.

```
playway_raw = """Data,Otwarcie,Najwyzszy,Najnizszy,Zamkniecie,Wolumen
2020-03-02,305,324.5,283.5,310,64081
2020-03-03,325.5,340.5,320,340.5,55496
2020-03-04,324,340.5,315,330,36152
2020-03-05,344,344,310,315,35992
2020-03-06,306.5,307,291,305,32539
2020-03-09,274,291,250,258,79402
2020-03-10,278,284.5,256,264,35700
2020-03-11,270,270,238.5,245,60445
2020-03-12,218,228,196,197,94031
2020-03-13,210,229,198.8,211,100412
2020-03-16,205,248,197.8,240.5,50659
2020-03-17,245,269,232.5,264,99480
2020-03-18,264,280,251,270,70136
2020-03-19,267,280,267,279.5,30732
2020-03-20,297.5,307,280,280.5,43426
2020-03-23,274,289,258,285,37098
2020-03-24,305,309,296.5,309,31939
2020-03-25,313,330,295,304,46724
2020-03-26,300,309,295.5,300,27213
2020-03-27,302,306.5,290,296,13466
2020-03-30,299,300,287,300,10316
2020-03-31,302.5,309,302,306.5,15698"""
```

Crate table named _playway_ and assign values from _playway_raw_.

In [6]:
playway_raw = """Data,Otwarcie,Najwyzszy,Najnizszy,Zamkniecie,Wolumen
2020-03-02,305,324.5,283.5,310,64081
2020-03-03,325.5,340.5,320,340.5,55496
2020-03-04,324,340.5,315,330,36152
2020-03-05,344,344,310,315,35992
2020-03-06,306.5,307,291,305,32539
2020-03-09,274,291,250,258,79402
2020-03-10,278,284.5,256,264,35700
2020-03-11,270,270,238.5,245,60445
2020-03-12,218,228,196,197,94031
2020-03-13,210,229,198.8,211,100412
2020-03-16,205,248,197.8,240.5,50659
2020-03-17,245,269,232.5,264,99480
2020-03-18,264,280,251,270,70136
2020-03-19,267,280,267,279.5,30732
2020-03-20,297.5,307,280,280.5,43426
2020-03-23,274,289,258,285,37098
2020-03-24,305,309,296.5,309,31939
2020-03-25,313,330,295,304,46724
2020-03-26,300,309,295.5,300,27213
2020-03-27,302,306.5,290,296,13466
2020-03-30,299,300,287,300,10316
2020-03-31,302.5,309,302,306.5,15698"""
# Solution
playway_raw = np.char.splitlines(playway_raw, keepends=None)
playway_raw =  np.array([element.split(',') for element in playway_raw.item() ])
playway_raw

array([['Data', 'Otwarcie', 'Najwyzszy', 'Najnizszy', 'Zamkniecie', 'Wolumen'],
       ['2020-03-02', '305', '324.5', '283.5', '310', '64081'],
       ['2020-03-03', '325.5', '340.5', '320', '340.5', '55496'],
       ['2020-03-04', '324', '340.5', '315', '330', '36152'],
       ['2020-03-05', '344', '344', '310', '315', '35992'],
       ['2020-03-06', '306.5', '307', '291', '305', '32539'],
       ['2020-03-09', '274', '291', '250', '258', '79402'],
       ['2020-03-10', '278', '284.5', '256', '264', '35700'],
       ['2020-03-11', '270', '270', '238.5', '245', '60445'],
       ['2020-03-12', '218', '228', '196', '197', '94031'],
       ['2020-03-13', '210', '229', '198.8', '211', '100412'],
       ['2020-03-16', '205', '248', '197.8', '240.5', '50659'],
       ['2020-03-17', '245', '269', '232.5', '264', '99480'],
       ['2020-03-18', '264', '280', '251', '270', '70136'],
       ['2020-03-19', '267', '280', '267', '279.5', '30732'],
       ['2020-03-20', '297.5', '307', '280', '280.5

Remove column named 'Data' and header from _playway_raw_ . Then convert result table to _float_.

__Excepted result:__



```
array([[   305. ,    324.5,    283.5,    310. ,  64081. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ],
       [   324. ,    340.5,    315. ,    330. ,  36152. ],
       [   344. ,    344. ,    310. ,    315. ,  35992. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ],
       [   270. ,    270. ,    238.5,    245. ,  60445. ],
       [   218. ,    228. ,    196. ,    197. ,  94031. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ],
       [   205. ,    248. ,    197.8,    240.5,  50659. ],
       [   245. ,    269. ,    232.5,    264. ,  99480. ],
       [   264. ,    280. ,    251. ,    270. ,  70136. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ],
       [   313. ,    330. ,    295. ,    304. ,  46724. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ],
       [   302. ,    306.5,    290. ,    296. ,  13466. ],
       [   299. ,    300. ,    287. ,    300. ,  10316. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ]])
```



In [7]:
# Solution
playway_values = playway_raw[1:,1:].astype(float)
playway_values

array([[   305. ,    324.5,    283.5,    310. ,  64081. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ],
       [   324. ,    340.5,    315. ,    330. ,  36152. ],
       [   344. ,    344. ,    310. ,    315. ,  35992. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ],
       [   270. ,    270. ,    238.5,    245. ,  60445. ],
       [   218. ,    228. ,    196. ,    197. ,  94031. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ],
       [   205. ,    248. ,    197.8,    240.5,  50659. ],
       [   245. ,    269. ,    232.5,    264. ,  99480. ],
       [   264. ,    280. ,    251. ,    270. ,  70136. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. 

### <a name='6'></a> Exercise 96
Using table _playway_values_ calculate average value from each of column. Round result to 2 digits.

In [8]:
# Solution
np.round(np.average(playway_values,axis = 0),2)

array([  283.14,   295.25,   268.69,   282.3 , 48688.05])

Using table _playway_values_ calculate minimal value from each of column. Round result to 2 digits.

In [9]:
# Solution
np.round(np.min(playway_values,axis = 0),2)

array([  205.,   228.,   196.,   197., 10316.])

Using table _playway_values_ calculate maximal value from each of column. Round result to 2 digits.

In [10]:
# Solution
np.round(np.max(playway_values,axis = 0),2)

array([   344. ,    344. ,    320. ,    340.5, 100412. ])

Compute difference between max and min values of each column

In [11]:
# Solution
np.round(np.max(playway_values,axis = 0),2) - np.round(np.min(playway_values,axis = 0),2)

array([  139. ,   116. ,   124. ,   143.5, 90096. ])

### <a name='7'></a> Exercise 97
Using table _playway_values_ compute new column with difference between minimal and maximal price.

__Excepted result:__


```
array([[   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5],
       [   324. ,    340.5,    315. ,    330. ,  36152. ,     25.5],
       [   344. ,    344. ,    310. ,    315. ,  35992. ,     34. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ,     16. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ,     28.5],
       [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5],
       [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ,     30.2],
       [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2],
       [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5],
       [   264. ,    280. ,    251. ,    270. ,  70136. ,     29. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ,     13. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ,     27. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ,     31. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ,     12.5],
       [   313. ,    330. ,    295. ,    304. ,  46724. ,     35. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ,     13.5],
       [   302. ,    306.5,    290. ,    296. ,  13466. ,     16.5],
       [   299. ,    300. ,    287. ,    300. ,  10316. ,     13. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ,      7. ]])
```



In [12]:
# Solution
np.c_[playway_values, (playway_values[:,1] - playway_values[:,2])]

array([[   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5],
       [   324. ,    340.5,    315. ,    330. ,  36152. ,     25.5],
       [   344. ,    344. ,    310. ,    315. ,  35992. ,     34. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ,     16. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ,     28.5],
       [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5],
       [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ,     30.2],
       [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2],
       [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5],
       [   264. ,    280. ,    251. ,    270. ,  70136. ,     29. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ,     13. ],
       [   297.5,    307. ,    280

### <a name='8'></a> Exercise 98
From the table _playway_values_ return rows,where close price was higher then 300.00 PLN.

In [13]:
# Solution
np.c_[playway_values, (playway_values[:,1] - playway_values[:,2])][playway_values[:,-2] > 300]

array([[  305. ,   324.5,   283.5,   310. , 64081. ,    41. ],
       [  325.5,   340.5,   320. ,   340.5, 55496. ,    20.5],
       [  324. ,   340.5,   315. ,   330. , 36152. ,    25.5],
       [  344. ,   344. ,   310. ,   315. , 35992. ,    34. ],
       [  306.5,   307. ,   291. ,   305. , 32539. ,    16. ],
       [  305. ,   309. ,   296.5,   309. , 31939. ,    12.5],
       [  313. ,   330. ,   295. ,   304. , 46724. ,    35. ],
       [  302.5,   309. ,   302. ,   306.5, 15698. ,     7. ]])

### <a name='9'></a> Exercise 99
From the table _playway_values_ return 10 first rows with highest value in column Wolumen in descending order.

In [14]:
# Solution
np.c_[playway_values, (playway_values[:,1] - playway_values[:,2])][playway_values[:,-1].argsort()][::-1][:10]

array([[   210. ,    229. ,    198.8,    211. , 100412. ,     30.2],
       [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5],
       [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ],
       [   264. ,    280. ,    251. ,    270. ,  70136. ,     29. ],
       [   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ],
       [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5],
       [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5],
       [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2],
       [   313. ,    330. ,    295. ,    304. ,  46724. ,     35. ]])

### <a name='10'></a> Exercise 100
To table _playway_values_ add 7th column,which will return 1 if cena zamknięcia > cena otwarcia else 0 .

__Oczekiwany wynik:__


```
array([[   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ,      1. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5,      1. ],
       [   324. ,    340.5,    315. ,    330. ,  36152. ,     25.5,      1. ],
       [   344. ,    344. ,    310. ,    315. ,  35992. ,     34. ,      0. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ,     16. ,      0. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ,      0. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ,     28.5,      0. ],
       [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5,      0. ],
       [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ,      0. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ,     30.2,      1. ],
       [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2,      1. ],
       [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5,      1. ],
       [   264. ,    280. ,    251. ,    270. ,  70136. ,     29. ,      1. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ,     13. ,      1. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ,     27. ,      0. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ,     31. ,      1. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ,     12.5,      1. ],
       [   313. ,    330. ,    295. ,    304. ,  46724. ,     35. ,      0. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ,     13.5,      0. ],
       [   302. ,    306.5,    290. ,    296. ,  13466. ,     16.5,      0. ],
       [   299. ,    300. ,    287. ,    300. ,  10316. ,     13. ,      1. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ,      7. ,      1. ]])
```



In [15]:
playway_values = np.c_[playway_values, (playway_values[:,1] - playway_values[:,2])]

# Solution
res_col = []
for element_nb in playway_values:
    if element_nb[0] < element_nb[-3]:
        res_col.append(1)
    else:
        res_col.append(0)
res_col

np.c_[playway_values, res_col]


array([[   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ,      1. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5,      1. ],
       [   324. ,    340.5,    315. ,    330. ,  36152. ,     25.5,      1. ],
       [   344. ,    344. ,    310. ,    315. ,  35992. ,     34. ,      0. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ,     16. ,      0. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ,      0. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ,     28.5,      0. ],
       [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5,      0. ],
       [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ,      0. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ,     30.2,      1. ],
       [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2,      1. ],
       [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5,      1. ],
       [   264. ,    280. ,    251. ,    270. ,  701